# Slices of a matrix

In [ ]:
import numpy as np
A = np.array([[2,0,1],[0,3,2]])

# Access first row of matrix A
print("first row of A is", A[0,:]) #: means grab everything

# Access the last column of matrix A
print("last column of A is", A[:,-1])  # -1 means the last item

# Access first and last column of A
print("first and last column of A are \n", A[:,[0,2]]) # Notice the use [] to reference multiple rows/columns

# Let us investigate whether A[:,-1] is a 2 x 1 column vector or 1 x 2 row vector !
A1 = np.array([[2],[3]])
A2 = np.array([[2,3]])
print("If\n",A1*(A[:,-1]), "printed, it means A[:,-1] is a row vector.")
print("if", A2*(A[:,-1]), "printed, it means A[:,-1] is a column vector.")

# Conclusion: Numpy do not really distinguish between row and column vectors.
# It uses whatever is convenient when doing multiplication with other matrices.

# A sub-matrix of A
print("A submatrix of A is", A[0:1, 1:3])

first row of A is [2 0 1]
last column of A is [1 2]
first and last column of A are 
 [[2 1]
 [0 2]]
If
 [[2 4]
 [3 6]] printed, it means A[:,-1] is a row vector.
if [[2 6]] printed, it means A[:,-1] is a column vector.
A submatrix of A is [[0 1]]


# Special Matrices


In [ ]:
import numpy as np
# Identity Matrix
print("Identity Matrix: \n", np.identity(3))

# Notice that AI = IA = A.
A = np.array([[2,0,1],[0,3,2]])
print("A*I = \n",np.matmul(A,np.identity(3)))

Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A*I = 
 [[2. 0. 1.]
 [0. 3. 2.]]


In [1]:
import numpy as np
A = np.array([[1, 21, 30], 
              [63 ,434, 3], 
              [54, 54, 56]])
print("The upper triangular part of A :\n", np.triu(A))
print("The lower triangular part of A :\n", np.tril(A))
print("transpose of A : \n", np.transpose(A))

The upper triangular part of A :
 [[  1  21  30]
 [  0 434   3]
 [  0   0  56]]
The lower triangular part of A :
 [[  1   0   0]
 [ 63 434   0]
 [ 54  54  56]]
transpose of A : 
 [[  1  63  54]
 [ 21 434  54]
 [ 30   3  56]]


# Matrix norm
$\color{#EF5645}{\text{Definition}}$: For a $m \times n$ matrix $A$, we define the matrix norm as:
$$||A|| = \sqrt{\sum_{i=1}^m \sum_{j=1}^n A_{ij}^2}.$$

$\color{#047C91}{\text{Example}}$: Compute the matrix norm of $A = \begin{bmatrix}
2 & 0 & 1\\
0 & 3 & 2 \end{bmatrix}.$

$||A|| = \sqrt{2^2 + 0^2 + 1^2 + 0^2 + 3^2 + 2^2} = \sqrt{18}$.

In [ ]:
# Matrix Norm
from numpy import linalg as LA
import numpy as np
A = np.array([[2,0,1],[0,3,2]])
print("A's norm is", LA.norm(A))
print("square root of 18 is", np.sqrt(18))

A's norm is 4.242640687119285
square root of 18 is 4.242640687119285


# Distance between two matrices

$\color{#EF5645}{\text{Definition}}$: The distance between two matrices $A$ and $B$ is defined as:
$$dist(A, B) = ||A - B||.$$

$\color{#047C91}{\text{Example}}$: Compute the distance between $A = \begin{bmatrix}
2 & 0 & 1\\
0 & 3 & 2 \end{bmatrix}$ and $B = \begin{bmatrix}
1 & 0 & 1\\
0 & 2 & 2 \end{bmatrix}.$

$||A - B|| = ||\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \end{bmatrix}|| = \sqrt{2}$.

In [ ]:
# Distance between 2 matrices
from numpy import linalg as LA
import numpy as np
A = np.array([[2,0,1],[0,3,2]])
B = np.array([[1,0,1],[0,2,2]])
print("Distance between A and B is", LA.norm(A - B))

Distance between A and B is 1.4142135623730951
